// <auto-generated />
using System;
using DAL.Dbcontext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(FacilityBookingDbContext))]
    [Migration("20251222073437_AddCampusImageUrl")]
    partial class AddCampusImageUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.Booking", b =>
                {
                    b.Property<string>("BookingId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("booking_id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("approved_by");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category");

                    b.Property<string>("CheckInImages")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("check_in_images");

                    b.Property<string>("CheckInNote")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("check_in_note");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("check_in_time");

                    b.Property<string>("CheckOutImages")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("check_out_images");

                    b.Property<string>("CheckOutNote")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("check_out_note");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("check_out_time");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_time");

                    b.Property<int?>("EstimatedAttendees")
                        .HasColumnType("int")
                        .HasColumnName("estimated_attendees");

                    b.Property<string>("FacilityId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("facility_id");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<string>("Purpose")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("purpose");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("SpecialRequirements")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("special_requirements");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending_Approval")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("user_id");

                    b.HasKey("BookingId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("FacilityId");

                    b.HasIndex("UserId");

                    b.ToTable("booking", (string)null);
                });

            modelBuilder.Entity("DAL.Models.BookingFeedback", b =>
                {
                    b.Property<string>("FeedbackId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("feedback_id");

                    b.Property<string>("BookingId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("booking_id");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("comments");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("IssueDescription")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("issue_description");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<bool>("ReportIssue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("report_issue");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("resolved_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("user_id");

                    b.HasKey("FeedbackId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("booking_feedback", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Campus", b =>
                {
                    b.Property<string>("CampusId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("campus_id");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("CampusId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("campus", (string)null);

                    b.HasData(
                        new
                        {
                            CampusId = "C0001",
                            Address = "Lô E2a-7, Đường D1, Khu Công nghệ cao, P.Long Thạnh Mỹ, Tp. Thủ Đức, TP.HCM",
                            CreatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 31, DateTimeKind.Utc).AddTicks(1367),
                            Email = "daihocfpt@fpt.edu.vn",
                            Name = "FPTU HCM Campus",
                            PhoneNumber = "028 7300 5588",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 31, DateTimeKind.Utc).AddTicks(1368)
                        },
                        new
                        {
                            CampusId = "C0002",
                            Address = "Số 1 Lưu Hữu Phước, Đông Hoà, Dĩ An, TP.HCM",
                            CreatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 31, DateTimeKind.Utc).AddTicks(1373),
                            Email = "nvhsv@fpt.edu.vn",
                            Name = "Nhà Văn Hóa Sinh Viên",
                            PhoneNumber = "028 7300 5589",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 31, DateTimeKind.Utc).AddTicks(1374)
                        });
                });

            modelBuilder.Entity("DAL.Models.Facility", b =>
                {
                    b.Property<string>("FacilityId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("facility_id");

                    b.Property<string>("Amenities")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("amenities");

                    b.Property<string>("CampusId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("campus_id");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("description");

                    b.Property<string>("FacilityManagerId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("facility_manager_id");

                    b.Property<string>("FloorNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("floor_number");

                    b.Property<int>("MaxConcurrentBookings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("max_concurrent_bookings");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("RoomNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("room_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Available")
                        .HasColumnName("status");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("type_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("FacilityId");

                    b.HasIndex("CampusId");

                    b.HasIndex("FacilityManagerId");

                    b.HasIndex("TypeId");

                    b.ToTable("facility", (string)null);

                    b.HasData(
                        new
                        {
                            FacilityId = "F00001",
                            CampusId = "C0001",
                            Capacity = 40,
                            CreatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 545, DateTimeKind.Utc).AddTicks(4098),
                            Description = "Phòng học lý thuyết",
                            FloorNumber = "1",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng A101",
                            RoomNumber = "A101",
                            Status = "Available",
                            TypeId = "FT0001",
                            UpdatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 545, DateTimeKind.Utc).AddTicks(4098)
                        },
                        new
                        {
                            FacilityId = "F00002",
                            CampusId = "C0001",
                            Capacity = 40,
                            CreatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 545, DateTimeKind.Utc).AddTicks(4103),
                            Description = "Phòng học lý thuyết",
                            FloorNumber = "1",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng A102",
                            RoomNumber = "A102",
                            Status = "Available",
                            TypeId = "FT0001",
                            UpdatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 545, DateTimeKind.Utc).AddTicks(4104)
                        },
                        new
                        {
                            FacilityId = "F00003",
                            CampusId = "C0001",
                            Capacity = 15,
                            CreatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 545, DateTimeKind.Utc).AddTicks(4108),
                            Description = "Phòng họp nhỏ",
                            FloorNumber = "2",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng họp B201",
                            RoomNumber = "B201",
                            Status = "Available",
                            TypeId = "FT0002",
                            UpdatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 545, DateTimeKind.Utc).AddTicks(4108)
                        },
                        new
                        {
                            FacilityId = "F00004",
                            CampusId = "C0001",
                            Capacity = 25,
                            CreatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 545, DateTimeKind.Utc).AddTicks(4112),
                            Description = "Phòng họp vừa",
                            FloorNumber = "2",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng họp B202",
                            RoomNumber = "B202",
                            Status = "Available",
                            TypeId = "FT0002",
                            UpdatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 545, DateTimeKind.Utc).AddTicks(4113)
                        },
                        new
                        {
                            FacilityId = "F00005",
                            CampusId = "C0001",
                            Capacity = 50,
                            CreatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 545, DateTimeKind.Utc).AddTicks(4116),
                            Description = "Phòng máy 50 máy",
                            FloorNumber = "3",
                            MaxConcurrentBookings = 1,
                            Name = "Lab máy tính C301",
                            RoomNumber = "C301",
                            Status = "Available",
                            TypeId = "FT0003",
                            UpdatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 545, DateTimeKind.Utc).AddTicks(4126)
                        },
                        new
                        {
                            FacilityId = "F00006",
                            CampusId = "C0001",
                            Capacity = 50,
                            CreatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 545, DateTimeKind.Utc).AddTicks(4130),
                            Description = "Phòng máy 50 máy",
                            FloorNumber = "3",
                            MaxConcurrentBookings = 1,
                            Name = "Lab máy tính C302",
                            RoomNumber = "C302",
                            Status = "Available",
                            TypeId = "FT0003",
                            UpdatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 545, DateTimeKind.Utc).AddTicks(4130)
                        },
                        new
                        {
                            FacilityId = "F00007",
                            CampusId = "C0001",
                            Capacity = 100,
                            CreatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 545, DateTimeKind.Utc).AddTicks(4134),
                            Description = "Sân bóng rổ ngoài trời",
                            FloorNumber = "0",
                            MaxConcurrentBookings = 2,
                            Name = "Sân bóng rổ",
                            RoomNumber = "Court1",
                            Status = "Available",
                            TypeId = "FT0004",
                            UpdatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 545, DateTimeKind.Utc).AddTicks(4135)
                        },
                        new
                        {
                            FacilityId = "F00008",
                            CampusId = "C0001",
                            Capacity = 80,
                            CreatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 545, DateTimeKind.Utc).AddTicks(4138),
                            Description = "4 sân cầu lông",
                            FloorNumber = "0",
                            MaxConcurrentBookings = 4,
                            Name = "Sân cầu lông",
                            RoomNumber = "Court2",
                            Status = "Available",
                            TypeId = "FT0004",
                            UpdatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 545, DateTimeKind.Utc).AddTicks(4139)
                        },
                        new
                        {
                            FacilityId = "F00011",
                            CampusId = "C0002",
                            Capacity = 30,
                            CreatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 545, DateTimeKind.Utc).AddTicks(4151),
                            Description = "Phòng sinh hoạt câu lạc bộ",
                            FloorNumber = "1",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng N101",
                            RoomNumber = "N101",
                            Status = "Available",
                            TypeId = "FT0001",
                            UpdatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 545, DateTimeKind.Utc).AddTicks(4152)
                        },
                        new
                        {
                            FacilityId = "F00012",
                            CampusId = "C0002",
                            Capacity = 30,
                            CreatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 545, DateTimeKind.Utc).AddTicks(4155),
                            Description = "Phòng sinh hoạt câu lạc bộ",
                            FloorNumber = "1",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng N102",
                            RoomNumber = "N102",
                            Status = "Available",
                            TypeId = "FT0001",
                            UpdatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 545, DateTimeKind.Utc).AddTicks(4156)
                        },
                        new
                        {
                            FacilityId = "F00013",
                            CampusId = "C0002",
                            Capacity = 15,
                            CreatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 545, DateTimeKind.Utc).AddTicks(4159),
                            Description = "Phòng họp Ban chủ nhiệm",
                            FloorNumber = "2",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng họp NVHSV 201",
                            RoomNumber = "N201",
                            Status = "Available",
                            TypeId = "FT0002",
                            UpdatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 545, DateTimeKind.Utc).AddTicks(4160)
                        },
                        new
                        {
                            FacilityId = "F00014",
                            CampusId = "C0002",
                            Capacity = 25,
                            CreatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 545, DateTimeKind.Utc).AddTicks(4163),
                            Description = "Phòng họp CLB",
                            FloorNumber = "2",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng họp NVHSV 202",
                            RoomNumber = "N202",
                            Status = "Available",
                            TypeId = "FT0002",
                            UpdatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 545, DateTimeKind.Utc).AddTicks(4164)
                        },
                        new
                        {
                            FacilityId = "F00015",
                            CampusId = "C0002",
                            Capacity = 20,
                            CreatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 545, DateTimeKind.Utc).AddTicks(4167),
                            Description = "Phòng sản xuất nội dung",
                            FloorNumber = "3",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng Media NVHSV",
                            RoomNumber = "N301",
                            Status = "Available",
                            TypeId = "FT0003",
                            UpdatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 545, DateTimeKind.Utc).AddTicks(4168)
                        },
                        new
                        {
                            FacilityId = "F00016",
                            CampusId = "C0002",
                            Capacity = 25,
                            CreatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 545, DateTimeKind.Utc).AddTicks(4171),
                            Description = "Phòng tập nhạc, ca hát",
                            FloorNumber = "3",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng Âm nhạc",
                            RoomNumber = "N302",
                            Status = "Available",
                            TypeId = "FT0003",
                            UpdatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 545, DateTimeKind.Utc).AddTicks(4172)
                        },
                        new
                        {
                            FacilityId = "F00017",
                            CampusId = "C0002",
                            Capacity = 200,
                            CreatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 545, DateTimeKind.Utc).AddTicks(4175),
                            Description = "Sân khấu tổ chức sự kiện",
                            FloorNumber = "0",
                            MaxConcurrentBookings = 1,
                            Name = "Sân khấu ngoài trời",
                            RoomNumber = "Stage1",
                            Status = "Available",
                            TypeId = "FT0004",
                            UpdatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 545, DateTimeKind.Utc).AddTicks(4175)
                        },
                        new
                        {
                            FacilityId = "F00018",
                            CampusId = "C0002",
                            Capacity = 50,
                            CreatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 545, DateTimeKind.Utc).AddTicks(4179),
                            Description = "Khu vực nướng ngoài trời",
                            FloorNumber = "0",
                            MaxConcurrentBookings = 2,
                            Name = "Khu vực BBQ",
                            RoomNumber = "BBQ1",
                            Status = "Available",
                            TypeId = "FT0004",
                            UpdatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 545, DateTimeKind.Utc).AddTicks(4179)
                        });
                });

            modelBuilder.Entity("DAL.Models.FacilityType", b =>
                {
                    b.Property<string>("TypeId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("type_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DefaultAmenities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DefaultCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("description");

                    b.Property<string>("IconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<int?>("TypicalDurationHours")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("TypeId");

                    b.ToTable("facility_type", (string)null);

                    b.HasData(
                        new
                        {
                            TypeId = "FT0001",
                            CreatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 32, DateTimeKind.Utc).AddTicks(8473),
                            Description = "Phòng học lý thuyết",
                            Name = "Phòng học",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 32, DateTimeKind.Utc).AddTicks(8475)
                        },
                        new
                        {
                            TypeId = "FT0002",
                            CreatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 32, DateTimeKind.Utc).AddTicks(8479),
                            Description = "Phòng họp",
                            Name = "Phòng họp",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 32, DateTimeKind.Utc).AddTicks(8480)
                        },
                        new
                        {
                            TypeId = "FT0003",
                            CreatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 32, DateTimeKind.Utc).AddTicks(8483),
                            Description = "Phòng máy tính",
                            Name = "Phòng máy tính",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 32, DateTimeKind.Utc).AddTicks(8484)
                        },
                        new
                        {
                            TypeId = "FT0004",
                            CreatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 32, DateTimeKind.Utc).AddTicks(8487),
                            Description = "Sân thể thao",
                            Name = "Sân thể thao",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 32, DateTimeKind.Utc).AddTicks(8488)
                        });
                });

            modelBuilder.Entity("DAL.Models.Notification", b =>
                {
                    b.Property<string>("NotificationId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("notification_id");

                    b.Property<string>("BookingId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("FeedbackId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("feedback_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("read_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Unread")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("user_id");

                    b.Property<string>("UserId1")
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("NotificationId");

                    b.HasIndex("BookingId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Role", b =>
                {
                    b.Property<string>("RoleId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("role_name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("RoleId");

                    b.ToTable("role", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = "RL0001",
                            CreatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 30, DateTimeKind.Utc).AddTicks(6392),
                            RoleName = "Sinh viên",
                            UpdatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 30, DateTimeKind.Utc).AddTicks(6393)
                        },
                        new
                        {
                            RoleId = "RL0002",
                            CreatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 30, DateTimeKind.Utc).AddTicks(6397),
                            RoleName = "Giảng viên",
                            UpdatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 30, DateTimeKind.Utc).AddTicks(6398)
                        },
                        new
                        {
                            RoleId = "RL0003",
                            CreatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 30, DateTimeKind.Utc).AddTicks(6401),
                            RoleName = "Quản trị viên cơ sở vật chất",
                            UpdatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 30, DateTimeKind.Utc).AddTicks(6401)
                        });
                });

            modelBuilder.Entity("DAL.Models.SystemSettings", b =>
                {
                    b.Property<string>("SettingKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("setting_key");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("description");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("setting_value");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("SettingKey");

                    b.HasIndex("SettingKey")
                        .IsUnique();

                    b.ToTable("system_settings", (string)null);
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("user_id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("EmailVerificationCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("email_verification_code");

                    b.Property<DateTime?>("EmailVerificationCodeExpiry")
                        .HasColumnType("datetime2")
                        .HasColumnName("email_verification_code_expiry");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("IsVerify")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Unverified")
                        .HasColumnName("is_verify");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("PasswordResetCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("password_reset_code");

                    b.Property<DateTime?>("PasswordResetCodeExpiry")
                        .HasColumnType("datetime2")
                        .HasColumnName("password_reset_code_expiry");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<string>("StudentId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("user_name");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[user_name] IS NOT NULL");

                    b.ToTable("user", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "U00001",
                            CreatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 201, DateTimeKind.Utc).AddTicks(7002),
                            Email = "student@fpt.edu.vn",
                            FullName = "Nguyễn Văn A",
                            IsVerify = "Unverified",
                            Password = "$2a$11$zBMA/TG1XML7dbh9siisr.4iLRaQwhGeiH.KS1t/vZFdM1fNFSqNi",
                            RoleId = "RL0001",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 201, DateTimeKind.Utc).AddTicks(7009),
                            UserName = "studentA"
                        },
                        new
                        {
                            UserId = "U00002",
                            CreatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 369, DateTimeKind.Utc).AddTicks(4458),
                            Email = "lecturer@fe.edu.vn",
                            FullName = "Trần Thị B",
                            IsVerify = "Unverified",
                            Password = "$2a$11$fd9nnfzhF.AQggTIGGEFzOETBDZynD6OnTC96.1gXwxOkTqtJXZyW",
                            RoleId = "RL0002",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 369, DateTimeKind.Utc).AddTicks(4465),
                            UserName = "lecturerB"
                        },
                        new
                        {
                            UserId = "U00003",
                            CreatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 541, DateTimeKind.Utc).AddTicks(6587),
                            Email = "admin@fpt.edu.vn",
                            FullName = "Quản trị viên hệ thống",
                            IsVerify = "Unverified",
                            Password = "$2a$11$kKI6TEYQPaDxV/HdviXr.uRICxy1aQlVyMxERNNX9OQmh3Ggw0soi",
                            RoleId = "RL0003",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 12, 22, 7, 34, 34, 541, DateTimeKind.Utc).AddTicks(6593),
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("DAL.Models.Booking", b =>
                {
                    b.HasOne("DAL.Models.User", "Approver")
                        .WithMany("ApprovedBookings")
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DAL.Models.Facility", "Facility")
                        .WithMany("Bookings")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Facility");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.BookingFeedback", b =>
                {
                    b.HasOne("DAL.Models.Booking", "Booking")
                        .WithOne("Feedback")
                        .HasForeignKey("DAL.Models.BookingFeedback", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.Facility", b =>
                {
                    b.HasOne("DAL.Models.Campus", "Campus")
                        .WithMany("Facilities")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "FacilityManager")
                        .WithMany("ManagedFacilities")
                        .HasForeignKey("FacilityManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DAL.Models.FacilityType", "FacilityType")
                        .WithMany("Facilities")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campus");

                    b.Navigation("FacilityManager");

                    b.Navigation("FacilityType");
                });

            modelBuilder.Entity("DAL.Models.Notification", b =>
                {
                    b.HasOne("DAL.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DAL.Models.BookingFeedback", "Feedback")
                        .WithMany()
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", null)
                        .WithMany("Notifications")
                        .HasForeignKey("UserId1");

                    b.Navigation("Booking");

                    b.Navigation("Feedback");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.HasOne("DAL.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DAL.Models.Booking", b =>
                {
                    b.Navigation("Feedback");
                });

            modelBuilder.Entity("DAL.Models.Campus", b =>
                {
                    b.Navigation("Facilities");
                });

            modelBuilder.Entity("DAL.Models.Facility", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("DAL.Models.FacilityType", b =>
                {
                    b.Navigation("Facilities");
                });

            modelBuilder.Entity("DAL.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Navigation("ApprovedBookings");

                    b.Navigation("Bookings");

                    b.Navigation("ManagedFacilities");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
