// <auto-generated />
using System;
using DAL.Dbcontext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(FacilityBookingDbContext))]
    [Migration("20251205000919_Initial6CoreModels")]
    partial class Initial6CoreModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.Booking", b =>
                {
                    b.Property<string>("BookingId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("booking_id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("approved_by");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("check_in_time");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("check_out_time");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_time");

                    b.Property<int?>("EstimatedAttendees")
                        .HasColumnType("int")
                        .HasColumnName("estimated_attendees");

                    b.Property<string>("FacilityId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("facility_id");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<string>("Purpose")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("purpose");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("SpecialRequirements")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("special_requirements");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("user_id");

                    b.HasKey("BookingId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("FacilityId");

                    b.HasIndex("UserId");

                    b.ToTable("booking", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Campus", b =>
                {
                    b.Property<string>("CampusId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("campus_id");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FacilityManagerId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("facility_manager_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("CampusId");

                    b.HasIndex("FacilityManagerId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("campus", (string)null);

                    b.HasData(
                        new
                        {
                            CampusId = "C0001",
                            Address = "Lô E2a-7, Đường D1, Khu Công nghệ cao, P.Long Thạnh Mỹ, Tp. Thủ Đức, TP.HCM",
                            CreatedAt = new DateTime(2025, 12, 5, 0, 9, 17, 680, DateTimeKind.Utc).AddTicks(8827),
                            Email = "daihocfpt@fpt.edu.vn",
                            Name = "FPTU HCM Campus",
                            PhoneNumber = "028 7300 5588",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 12, 5, 0, 9, 17, 680, DateTimeKind.Utc).AddTicks(8828)
                        },
                        new
                        {
                            CampusId = "C0002",
                            Address = "Khu đô thị Khoa học và Giáo dục Quy Hòa, Phường Ghềnh Ráng, TP. Quy Nhơn, Bình Định",
                            CreatedAt = new DateTime(2025, 12, 5, 0, 9, 17, 680, DateTimeKind.Utc).AddTicks(8833),
                            Email = "daihocfpt.qn@fpt.edu.vn",
                            Name = "FPTU Quy Nhơn Campus",
                            PhoneNumber = "0256 7300 999",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 12, 5, 0, 9, 17, 680, DateTimeKind.Utc).AddTicks(8834)
                        });
                });

            modelBuilder.Entity("DAL.Models.Facility", b =>
                {
                    b.Property<string>("FacilityId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("facility_id");

                    b.Property<string>("Amenities")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("amenities");

                    b.Property<string>("CampusId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("campus_id");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("description");

                    b.Property<string>("FacilityManagerId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("facility_manager_id");

                    b.Property<string>("FloorNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("floor_number");

                    b.Property<int>("MaxConcurrentBookings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("max_concurrent_bookings");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("RoomNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("room_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Available")
                        .HasColumnName("status");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("type_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("FacilityId");

                    b.HasIndex("CampusId");

                    b.HasIndex("FacilityManagerId");

                    b.HasIndex("TypeId");

                    b.ToTable("facility", (string)null);

                    b.HasData(
                        new
                        {
                            FacilityId = "F00001",
                            CampusId = "C0001",
                            Capacity = 40,
                            CreatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(1945),
                            Description = "Phòng học lý thuyết",
                            FloorNumber = "1",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng A101",
                            RoomNumber = "A101",
                            Status = "Available",
                            TypeId = "FT0001",
                            UpdatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(1946)
                        },
                        new
                        {
                            FacilityId = "F00002",
                            CampusId = "C0001",
                            Capacity = 40,
                            CreatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(1952),
                            Description = "Phòng học lý thuyết",
                            FloorNumber = "1",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng A102",
                            RoomNumber = "A102",
                            Status = "Available",
                            TypeId = "FT0001",
                            UpdatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(1952)
                        },
                        new
                        {
                            FacilityId = "F00003",
                            CampusId = "C0001",
                            Capacity = 15,
                            CreatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(1956),
                            Description = "Phòng họp nhỏ",
                            FloorNumber = "2",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng họp B201",
                            RoomNumber = "B201",
                            Status = "Available",
                            TypeId = "FT0002",
                            UpdatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(1957)
                        },
                        new
                        {
                            FacilityId = "F00004",
                            CampusId = "C0001",
                            Capacity = 25,
                            CreatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(1961),
                            Description = "Phòng họp vừa",
                            FloorNumber = "2",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng họp B202",
                            RoomNumber = "B202",
                            Status = "Available",
                            TypeId = "FT0002",
                            UpdatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(1961)
                        },
                        new
                        {
                            FacilityId = "F00005",
                            CampusId = "C0001",
                            Capacity = 50,
                            CreatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(1965),
                            Description = "Phòng máy 50 máy",
                            FloorNumber = "3",
                            MaxConcurrentBookings = 1,
                            Name = "Lab máy tính C301",
                            RoomNumber = "C301",
                            Status = "Available",
                            TypeId = "FT0003",
                            UpdatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(1971)
                        },
                        new
                        {
                            FacilityId = "F00006",
                            CampusId = "C0001",
                            Capacity = 50,
                            CreatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(1975),
                            Description = "Phòng máy 50 máy",
                            FloorNumber = "3",
                            MaxConcurrentBookings = 1,
                            Name = "Lab máy tính C302",
                            RoomNumber = "C302",
                            Status = "Available",
                            TypeId = "FT0003",
                            UpdatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(1975)
                        },
                        new
                        {
                            FacilityId = "F00007",
                            CampusId = "C0001",
                            Capacity = 100,
                            CreatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(1979),
                            Description = "Sân bóng rổ ngoài trời",
                            FloorNumber = "0",
                            MaxConcurrentBookings = 2,
                            Name = "Sân bóng rổ",
                            RoomNumber = "Court1",
                            Status = "Available",
                            TypeId = "FT0004",
                            UpdatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(1980)
                        },
                        new
                        {
                            FacilityId = "F00008",
                            CampusId = "C0001",
                            Capacity = 80,
                            CreatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(1984),
                            Description = "4 sân cầu lông",
                            FloorNumber = "0",
                            MaxConcurrentBookings = 4,
                            Name = "Sân cầu lông",
                            RoomNumber = "Court2",
                            Status = "Available",
                            TypeId = "FT0004",
                            UpdatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(1984)
                        },
                        new
                        {
                            FacilityId = "F00009",
                            CampusId = "C0001",
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(2028),
                            Description = "Hội trường lớn",
                            FloorNumber = "1",
                            MaxConcurrentBookings = 1,
                            Name = "Hội trường A",
                            RoomNumber = "HallA",
                            Status = "Available",
                            TypeId = "FT0005",
                            UpdatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(2029)
                        },
                        new
                        {
                            FacilityId = "F00010",
                            CampusId = "C0001",
                            Capacity = 200,
                            CreatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(2033),
                            Description = "Hội trường nhỏ",
                            FloorNumber = "1",
                            MaxConcurrentBookings = 1,
                            Name = "Hội trường B",
                            RoomNumber = "HallB",
                            Status = "Available",
                            TypeId = "FT0005",
                            UpdatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(2033)
                        },
                        new
                        {
                            FacilityId = "F00011",
                            CampusId = "C0002",
                            Capacity = 35,
                            CreatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(2115),
                            Description = "Phòng học lý thuyết",
                            FloorNumber = "1",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng QN101",
                            RoomNumber = "QN101",
                            Status = "Available",
                            TypeId = "FT0001",
                            UpdatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(2116)
                        },
                        new
                        {
                            FacilityId = "F00012",
                            CampusId = "C0002",
                            Capacity = 35,
                            CreatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(2119),
                            Description = "Phòng học lý thuyết",
                            FloorNumber = "1",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng QN102",
                            RoomNumber = "QN102",
                            Status = "Available",
                            TypeId = "FT0001",
                            UpdatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(2120)
                        },
                        new
                        {
                            FacilityId = "F00013",
                            CampusId = "C0002",
                            Capacity = 12,
                            CreatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(2124),
                            Description = "Phòng họp nhỏ",
                            FloorNumber = "2",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng họp QN201",
                            RoomNumber = "QN201",
                            Status = "Available",
                            TypeId = "FT0002",
                            UpdatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(2125)
                        },
                        new
                        {
                            FacilityId = "F00014",
                            CampusId = "C0002",
                            Capacity = 20,
                            CreatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(2128),
                            Description = "Phòng họp vừa",
                            FloorNumber = "2",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng họp QN202",
                            RoomNumber = "QN202",
                            Status = "Available",
                            TypeId = "FT0002",
                            UpdatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(2129)
                        },
                        new
                        {
                            FacilityId = "F00015",
                            CampusId = "C0002",
                            Capacity = 40,
                            CreatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(2133),
                            Description = "Phòng máy 40 máy",
                            FloorNumber = "3",
                            MaxConcurrentBookings = 1,
                            Name = "Lab máy tính QN301",
                            RoomNumber = "QN301",
                            Status = "Available",
                            TypeId = "FT0003",
                            UpdatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(2133)
                        },
                        new
                        {
                            FacilityId = "F00016",
                            CampusId = "C0002",
                            Capacity = 40,
                            CreatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(2137),
                            Description = "Phòng máy 40 máy",
                            FloorNumber = "3",
                            MaxConcurrentBookings = 1,
                            Name = "Lab máy tính QN302",
                            RoomNumber = "QN302",
                            Status = "Available",
                            TypeId = "FT0003",
                            UpdatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(2137)
                        },
                        new
                        {
                            FacilityId = "F00017",
                            CampusId = "C0002",
                            Capacity = 50,
                            CreatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(2141),
                            Description = "Sân bóng đá 5 người",
                            FloorNumber = "0",
                            MaxConcurrentBookings = 2,
                            Name = "Sân bóng đá",
                            RoomNumber = "Court1",
                            Status = "Available",
                            TypeId = "FT0004",
                            UpdatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(2141)
                        },
                        new
                        {
                            FacilityId = "F00018",
                            CampusId = "C0002",
                            Capacity = 40,
                            CreatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(2145),
                            Description = "2 sân tennis",
                            FloorNumber = "0",
                            MaxConcurrentBookings = 2,
                            Name = "Sân tennis",
                            RoomNumber = "Court2",
                            Status = "Available",
                            TypeId = "FT0004",
                            UpdatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(2146)
                        },
                        new
                        {
                            FacilityId = "F00019",
                            CampusId = "C0002",
                            Capacity = 400,
                            CreatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(2149),
                            Description = "Hội trường chính",
                            FloorNumber = "1",
                            MaxConcurrentBookings = 1,
                            Name = "Hội trường QN",
                            RoomNumber = "HallQN",
                            Status = "Available",
                            TypeId = "FT0005",
                            UpdatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(2150)
                        },
                        new
                        {
                            FacilityId = "F00020",
                            CampusId = "C0002",
                            Capacity = 100,
                            CreatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(2153),
                            Description = "Phòng hội thảo",
                            FloorNumber = "2",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng đa năng QN",
                            RoomNumber = "MultiQN",
                            Status = "Available",
                            TypeId = "FT0005",
                            UpdatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 324, DateTimeKind.Utc).AddTicks(2154)
                        });
                });

            modelBuilder.Entity("DAL.Models.FacilityType", b =>
                {
                    b.Property<string>("TypeId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("type_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DefaultAmenities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DefaultCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("description");

                    b.Property<string>("IconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("TypicalDurationHours")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("TypeId");

                    b.ToTable("facility_type", (string)null);

                    b.HasData(
                        new
                        {
                            TypeId = "FT0001",
                            CreatedAt = new DateTime(2025, 12, 5, 0, 9, 17, 681, DateTimeKind.Utc).AddTicks(9499),
                            Description = "Phòng học lý thuyết",
                            Name = "Classroom",
                            UpdatedAt = new DateTime(2025, 12, 5, 0, 9, 17, 681, DateTimeKind.Utc).AddTicks(9500)
                        },
                        new
                        {
                            TypeId = "FT0002",
                            CreatedAt = new DateTime(2025, 12, 5, 0, 9, 17, 681, DateTimeKind.Utc).AddTicks(9503),
                            Description = "Phòng họp",
                            Name = "Meeting Room",
                            UpdatedAt = new DateTime(2025, 12, 5, 0, 9, 17, 681, DateTimeKind.Utc).AddTicks(9504)
                        },
                        new
                        {
                            TypeId = "FT0003",
                            CreatedAt = new DateTime(2025, 12, 5, 0, 9, 17, 681, DateTimeKind.Utc).AddTicks(9507),
                            Description = "Phòng máy tính",
                            Name = "Computer Lab",
                            UpdatedAt = new DateTime(2025, 12, 5, 0, 9, 17, 681, DateTimeKind.Utc).AddTicks(9507)
                        },
                        new
                        {
                            TypeId = "FT0004",
                            CreatedAt = new DateTime(2025, 12, 5, 0, 9, 17, 681, DateTimeKind.Utc).AddTicks(9510),
                            Description = "Sân thể thao",
                            Name = "Sports Court",
                            UpdatedAt = new DateTime(2025, 12, 5, 0, 9, 17, 681, DateTimeKind.Utc).AddTicks(9510)
                        },
                        new
                        {
                            TypeId = "FT0005",
                            CreatedAt = new DateTime(2025, 12, 5, 0, 9, 17, 681, DateTimeKind.Utc).AddTicks(9513),
                            Description = "Hội trường",
                            Name = "Auditorium",
                            UpdatedAt = new DateTime(2025, 12, 5, 0, 9, 17, 681, DateTimeKind.Utc).AddTicks(9513)
                        });
                });

            modelBuilder.Entity("DAL.Models.Role", b =>
                {
                    b.Property<string>("RoleId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("role_name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("RoleId");

                    b.ToTable("role", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = "RL0001",
                            CreatedAt = new DateTime(2025, 12, 5, 0, 9, 17, 676, DateTimeKind.Utc).AddTicks(8829),
                            RoleName = "Student",
                            UpdatedAt = new DateTime(2025, 12, 5, 0, 9, 17, 676, DateTimeKind.Utc).AddTicks(8830)
                        },
                        new
                        {
                            RoleId = "RL0002",
                            CreatedAt = new DateTime(2025, 12, 5, 0, 9, 17, 676, DateTimeKind.Utc).AddTicks(8834),
                            RoleName = "Lecturer",
                            UpdatedAt = new DateTime(2025, 12, 5, 0, 9, 17, 676, DateTimeKind.Utc).AddTicks(8835)
                        },
                        new
                        {
                            RoleId = "RL0003",
                            CreatedAt = new DateTime(2025, 12, 5, 0, 9, 17, 676, DateTimeKind.Utc).AddTicks(8837),
                            RoleName = "Facility_Admin",
                            UpdatedAt = new DateTime(2025, 12, 5, 0, 9, 17, 676, DateTimeKind.Utc).AddTicks(8838)
                        });
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("user_id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("CampusId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("campus_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("EmailVerificationCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("email_verification_code");

                    b.Property<DateTime?>("EmailVerificationCodeExpiry")
                        .HasColumnType("datetime2")
                        .HasColumnName("email_verification_code_expiry");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("IsVerify")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Unverified")
                        .HasColumnName("is_verify");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("PasswordResetCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("password_reset_code");

                    b.Property<DateTime?>("PasswordResetCodeExpiry")
                        .HasColumnType("datetime2")
                        .HasColumnName("password_reset_code_expiry");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("user_name");

                    b.HasKey("UserId");

                    b.HasIndex("CampusId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[user_name] IS NOT NULL");

                    b.ToTable("user", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "U00001",
                            CampusId = "C0001",
                            CreatedAt = new DateTime(2025, 12, 5, 0, 9, 17, 907, DateTimeKind.Utc).AddTicks(6718),
                            Email = "student@fpt.edu.vn",
                            FullName = "Nguyễn Văn A",
                            IsVerify = "Unverified",
                            Password = "$2a$11$ZZJd00NzYPM9jhH5PpKtCOJ4d4aR64wuuKjWiQKMJxxHFoQZYbkWq",
                            RoleId = "RL0001",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 12, 5, 0, 9, 17, 907, DateTimeKind.Utc).AddTicks(6723),
                            UserName = "studentA"
                        },
                        new
                        {
                            UserId = "U00002",
                            CampusId = "C0001",
                            CreatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 112, DateTimeKind.Utc).AddTicks(4329),
                            Email = "lecturer@fe.edu.vn",
                            FullName = "Trần Thị B",
                            IsVerify = "Unverified",
                            Password = "$2a$11$9uDyDC0uIXxTIyHfyS0Pbu.DkQm.EKWMriuZZgZkK6/.2qyYOuY.a",
                            RoleId = "RL0002",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 112, DateTimeKind.Utc).AddTicks(4336),
                            UserName = "lecturerB"
                        },
                        new
                        {
                            UserId = "U00003",
                            CampusId = "C0001",
                            CreatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 321, DateTimeKind.Utc).AddTicks(7761),
                            Email = "admin@fpt.edu.vn",
                            FullName = "Admin System",
                            IsVerify = "Unverified",
                            Password = "$2a$11$3O.yiPJ7fOCo9wlrUFfZ8./r2AnqYqF67uBBed5rl1LNl1BHI/G3u",
                            RoleId = "RL0003",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 12, 5, 0, 9, 18, 321, DateTimeKind.Utc).AddTicks(7765),
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("DAL.Models.Booking", b =>
                {
                    b.HasOne("DAL.Models.User", "Approver")
                        .WithMany("ApprovedBookings")
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DAL.Models.Facility", "Facility")
                        .WithMany("Bookings")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Facility");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.Campus", b =>
                {
                    b.HasOne("DAL.Models.User", "FacilityManager")
                        .WithMany("ManagedCampuses")
                        .HasForeignKey("FacilityManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FacilityManager");
                });

            modelBuilder.Entity("DAL.Models.Facility", b =>
                {
                    b.HasOne("DAL.Models.Campus", "Campus")
                        .WithMany("Facilities")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "FacilityManager")
                        .WithMany("ManagedFacilities")
                        .HasForeignKey("FacilityManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DAL.Models.FacilityType", "FacilityType")
                        .WithMany("Facilities")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campus");

                    b.Navigation("FacilityManager");

                    b.Navigation("FacilityType");
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.HasOne("DAL.Models.Campus", "Campus")
                        .WithMany("Users")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campus");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DAL.Models.Campus", b =>
                {
                    b.Navigation("Facilities");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DAL.Models.Facility", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("DAL.Models.FacilityType", b =>
                {
                    b.Navigation("Facilities");
                });

            modelBuilder.Entity("DAL.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Navigation("ApprovedBookings");

                    b.Navigation("Bookings");

                    b.Navigation("ManagedCampuses");

                    b.Navigation("ManagedFacilities");
                });
#pragma warning restore 612, 618
        }
    }
}
