// <auto-generated />
using System;
using DAL.Dbcontext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(FacilityBookingDbContext))]
    [Migration("20251210022122_AddNotificationModel")]
    partial class AddNotificationModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.Booking", b =>
                {
                    b.Property<string>("BookingId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("booking_id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("approved_by");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("check_in_time");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("check_out_time");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_time");

                    b.Property<int?>("EstimatedAttendees")
                        .HasColumnType("int")
                        .HasColumnName("estimated_attendees");

                    b.Property<string>("FacilityId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("facility_id");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<string>("Purpose")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("purpose");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("SpecialRequirements")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("special_requirements");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("user_id");

                    b.HasKey("BookingId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("FacilityId");

                    b.HasIndex("UserId");

                    b.ToTable("booking", (string)null);
                });

            modelBuilder.Entity("DAL.Models.BookingFeedback", b =>
                {
                    b.Property<string>("FeedbackId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("feedback_id");

                    b.Property<string>("BookingId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("booking_id");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("comments");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("IssueDescription")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("issue_description");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<bool>("ReportIssue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("report_issue");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("resolved_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("user_id");

                    b.HasKey("FeedbackId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("booking_feedback", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Campus", b =>
                {
                    b.Property<string>("CampusId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("campus_id");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("CampusId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("campus", (string)null);

                    b.HasData(
                        new
                        {
                            CampusId = "C0001",
                            Address = "Lô E2a-7, Đường D1, Khu Công nghệ cao, P.Long Thạnh Mỹ, Tp. Thủ Đức, TP.HCM",
                            CreatedAt = new DateTime(2025, 12, 10, 2, 21, 21, 898, DateTimeKind.Utc).AddTicks(7459),
                            Email = "daihocfpt@fpt.edu.vn",
                            Name = "FPTU HCM Campus",
                            PhoneNumber = "028 7300 5588",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 12, 10, 2, 21, 21, 898, DateTimeKind.Utc).AddTicks(7460)
                        },
                        new
                        {
                            CampusId = "C0002",
                            Address = "Số 1 Lưu Hữu Phước, Đông Hoà, Dĩ An, TP.HCM",
                            CreatedAt = new DateTime(2025, 12, 10, 2, 21, 21, 898, DateTimeKind.Utc).AddTicks(7465),
                            Email = "nvhsv@fpt.edu.vn",
                            Name = "Nhà Văn Hóa Sinh Viên",
                            PhoneNumber = "028 7300 5589",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 12, 10, 2, 21, 21, 898, DateTimeKind.Utc).AddTicks(7466)
                        });
                });

            modelBuilder.Entity("DAL.Models.Facility", b =>
                {
                    b.Property<string>("FacilityId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("facility_id");

                    b.Property<string>("Amenities")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("amenities");

                    b.Property<string>("CampusId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("campus_id");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("description");

                    b.Property<string>("FacilityManagerId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("facility_manager_id");

                    b.Property<string>("FloorNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("floor_number");

                    b.Property<int>("MaxConcurrentBookings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("max_concurrent_bookings");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("RoomNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("room_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Available")
                        .HasColumnName("status");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("type_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("FacilityId");

                    b.HasIndex("CampusId");

                    b.HasIndex("FacilityManagerId");

                    b.HasIndex("TypeId");

                    b.ToTable("facility", (string)null);

                    b.HasData(
                        new
                        {
                            FacilityId = "F00001",
                            CampusId = "C0001",
                            Capacity = 40,
                            CreatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9268),
                            Description = "Phòng học lý thuyết",
                            FloorNumber = "1",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng A101",
                            RoomNumber = "A101",
                            Status = "Available",
                            TypeId = "FT0001",
                            UpdatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9269)
                        },
                        new
                        {
                            FacilityId = "F00002",
                            CampusId = "C0001",
                            Capacity = 40,
                            CreatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9274),
                            Description = "Phòng học lý thuyết",
                            FloorNumber = "1",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng A102",
                            RoomNumber = "A102",
                            Status = "Available",
                            TypeId = "FT0001",
                            UpdatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9275)
                        },
                        new
                        {
                            FacilityId = "F00003",
                            CampusId = "C0001",
                            Capacity = 15,
                            CreatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9340),
                            Description = "Phòng họp nhỏ",
                            FloorNumber = "2",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng họp B201",
                            RoomNumber = "B201",
                            Status = "Available",
                            TypeId = "FT0002",
                            UpdatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9340)
                        },
                        new
                        {
                            FacilityId = "F00004",
                            CampusId = "C0001",
                            Capacity = 25,
                            CreatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9344),
                            Description = "Phòng họp vừa",
                            FloorNumber = "2",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng họp B202",
                            RoomNumber = "B202",
                            Status = "Available",
                            TypeId = "FT0002",
                            UpdatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9345)
                        },
                        new
                        {
                            FacilityId = "F00005",
                            CampusId = "C0001",
                            Capacity = 50,
                            CreatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9348),
                            Description = "Phòng máy 50 máy",
                            FloorNumber = "3",
                            MaxConcurrentBookings = 1,
                            Name = "Lab máy tính C301",
                            RoomNumber = "C301",
                            Status = "Available",
                            TypeId = "FT0003",
                            UpdatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9359)
                        },
                        new
                        {
                            FacilityId = "F00006",
                            CampusId = "C0001",
                            Capacity = 50,
                            CreatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9363),
                            Description = "Phòng máy 50 máy",
                            FloorNumber = "3",
                            MaxConcurrentBookings = 1,
                            Name = "Lab máy tính C302",
                            RoomNumber = "C302",
                            Status = "Available",
                            TypeId = "FT0003",
                            UpdatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9364)
                        },
                        new
                        {
                            FacilityId = "F00007",
                            CampusId = "C0001",
                            Capacity = 100,
                            CreatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9367),
                            Description = "Sân bóng rổ ngoài trời",
                            FloorNumber = "0",
                            MaxConcurrentBookings = 2,
                            Name = "Sân bóng rổ",
                            RoomNumber = "Court1",
                            Status = "Available",
                            TypeId = "FT0004",
                            UpdatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9368)
                        },
                        new
                        {
                            FacilityId = "F00008",
                            CampusId = "C0001",
                            Capacity = 80,
                            CreatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9372),
                            Description = "4 sân cầu lông",
                            FloorNumber = "0",
                            MaxConcurrentBookings = 4,
                            Name = "Sân cầu lông",
                            RoomNumber = "Court2",
                            Status = "Available",
                            TypeId = "FT0004",
                            UpdatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9372)
                        },
                        new
                        {
                            FacilityId = "F00009",
                            CampusId = "C0001",
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9376),
                            Description = "Hội trường lớn",
                            FloorNumber = "1",
                            MaxConcurrentBookings = 1,
                            Name = "Hội trường A",
                            RoomNumber = "HallA",
                            Status = "Available",
                            TypeId = "FT0005",
                            UpdatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9376)
                        },
                        new
                        {
                            FacilityId = "F00010",
                            CampusId = "C0001",
                            Capacity = 200,
                            CreatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9380),
                            Description = "Hội trường nhỏ",
                            FloorNumber = "1",
                            MaxConcurrentBookings = 1,
                            Name = "Hội trường B",
                            RoomNumber = "HallB",
                            Status = "Available",
                            TypeId = "FT0005",
                            UpdatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9380)
                        },
                        new
                        {
                            FacilityId = "F00011",
                            CampusId = "C0002",
                            Capacity = 30,
                            CreatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9450),
                            Description = "Phòng sinh hoạt câu lạc bộ",
                            FloorNumber = "1",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng N101",
                            RoomNumber = "N101",
                            Status = "Available",
                            TypeId = "FT0001",
                            UpdatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9451)
                        },
                        new
                        {
                            FacilityId = "F00012",
                            CampusId = "C0002",
                            Capacity = 30,
                            CreatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9455),
                            Description = "Phòng sinh hoạt câu lạc bộ",
                            FloorNumber = "1",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng N102",
                            RoomNumber = "N102",
                            Status = "Available",
                            TypeId = "FT0001",
                            UpdatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9455)
                        },
                        new
                        {
                            FacilityId = "F00013",
                            CampusId = "C0002",
                            Capacity = 15,
                            CreatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9459),
                            Description = "Phòng họp Ban chủ nhiệm",
                            FloorNumber = "2",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng họp NVHSV 201",
                            RoomNumber = "N201",
                            Status = "Available",
                            TypeId = "FT0002",
                            UpdatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9459)
                        },
                        new
                        {
                            FacilityId = "F00014",
                            CampusId = "C0002",
                            Capacity = 25,
                            CreatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9463),
                            Description = "Phòng họp CLB",
                            FloorNumber = "2",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng họp NVHSV 202",
                            RoomNumber = "N202",
                            Status = "Available",
                            TypeId = "FT0002",
                            UpdatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9463)
                        },
                        new
                        {
                            FacilityId = "F00015",
                            CampusId = "C0002",
                            Capacity = 20,
                            CreatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9467),
                            Description = "Phòng sản xuất nội dung",
                            FloorNumber = "3",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng Media NVHSV",
                            RoomNumber = "N301",
                            Status = "Available",
                            TypeId = "FT0003",
                            UpdatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9467)
                        },
                        new
                        {
                            FacilityId = "F00016",
                            CampusId = "C0002",
                            Capacity = 25,
                            CreatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9471),
                            Description = "Phòng tập nhạc, ca hát",
                            FloorNumber = "3",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng Âm nhạc",
                            RoomNumber = "N302",
                            Status = "Available",
                            TypeId = "FT0003",
                            UpdatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9471)
                        },
                        new
                        {
                            FacilityId = "F00017",
                            CampusId = "C0002",
                            Capacity = 200,
                            CreatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9475),
                            Description = "Sân khấu tổ chức sự kiện",
                            FloorNumber = "0",
                            MaxConcurrentBookings = 1,
                            Name = "Sân khấu ngoài trời",
                            RoomNumber = "Stage1",
                            Status = "Available",
                            TypeId = "FT0004",
                            UpdatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9475)
                        },
                        new
                        {
                            FacilityId = "F00018",
                            CampusId = "C0002",
                            Capacity = 50,
                            CreatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9479),
                            Description = "Khu vực nướng ngoài trời",
                            FloorNumber = "0",
                            MaxConcurrentBookings = 2,
                            Name = "Khu vực BBQ",
                            RoomNumber = "BBQ1",
                            Status = "Available",
                            TypeId = "FT0004",
                            UpdatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9479)
                        },
                        new
                        {
                            FacilityId = "F00019",
                            CampusId = "C0002",
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9482),
                            Description = "Hội trường tổ chức sự kiện lớn",
                            FloorNumber = "1",
                            MaxConcurrentBookings = 1,
                            Name = "Hội trường NVHSV",
                            RoomNumber = "HallNVH",
                            Status = "Available",
                            TypeId = "FT0005",
                            UpdatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9483)
                        },
                        new
                        {
                            FacilityId = "F00020",
                            CampusId = "C0002",
                            Capacity = 80,
                            CreatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9486),
                            Description = "Phòng tổ chức workshop, training",
                            FloorNumber = "2",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng Workshop",
                            RoomNumber = "Workshop1",
                            Status = "Available",
                            TypeId = "FT0005",
                            UpdatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 376, DateTimeKind.Utc).AddTicks(9487)
                        });
                });

            modelBuilder.Entity("DAL.Models.FacilityType", b =>
                {
                    b.Property<string>("TypeId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("type_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DefaultAmenities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DefaultCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("description");

                    b.Property<string>("IconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<int?>("TypicalDurationHours")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("TypeId");

                    b.ToTable("facility_type", (string)null);

                    b.HasData(
                        new
                        {
                            TypeId = "FT0001",
                            CreatedAt = new DateTime(2025, 12, 10, 2, 21, 21, 900, DateTimeKind.Utc).AddTicks(7835),
                            Description = "Phòng học lý thuyết",
                            Name = "Phòng học",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 12, 10, 2, 21, 21, 900, DateTimeKind.Utc).AddTicks(7837)
                        },
                        new
                        {
                            TypeId = "FT0002",
                            CreatedAt = new DateTime(2025, 12, 10, 2, 21, 21, 900, DateTimeKind.Utc).AddTicks(7840),
                            Description = "Phòng họp",
                            Name = "Phòng họp",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 12, 10, 2, 21, 21, 900, DateTimeKind.Utc).AddTicks(7841)
                        },
                        new
                        {
                            TypeId = "FT0003",
                            CreatedAt = new DateTime(2025, 12, 10, 2, 21, 21, 900, DateTimeKind.Utc).AddTicks(7844),
                            Description = "Phòng máy tính",
                            Name = "Phòng máy tính",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 12, 10, 2, 21, 21, 900, DateTimeKind.Utc).AddTicks(7845)
                        },
                        new
                        {
                            TypeId = "FT0004",
                            CreatedAt = new DateTime(2025, 12, 10, 2, 21, 21, 900, DateTimeKind.Utc).AddTicks(7848),
                            Description = "Sân thể thao",
                            Name = "Sân thể thao",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 12, 10, 2, 21, 21, 900, DateTimeKind.Utc).AddTicks(7849)
                        },
                        new
                        {
                            TypeId = "FT0005",
                            CreatedAt = new DateTime(2025, 12, 10, 2, 21, 21, 900, DateTimeKind.Utc).AddTicks(7910),
                            Description = "Hội trường",
                            Name = "Hội trường",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 12, 10, 2, 21, 21, 900, DateTimeKind.Utc).AddTicks(7911)
                        });
                });

            modelBuilder.Entity("DAL.Models.Notification", b =>
                {
                    b.Property<string>("NotificationId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("notification_id");

                    b.Property<string>("BookingId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("FeedbackId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("feedback_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("read_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Unread")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("user_id");

                    b.Property<string>("UserId1")
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("NotificationId");

                    b.HasIndex("BookingId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Role", b =>
                {
                    b.Property<string>("RoleId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("role_name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("RoleId");

                    b.ToTable("role", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = "RL0001",
                            CreatedAt = new DateTime(2025, 12, 10, 2, 21, 21, 898, DateTimeKind.Utc).AddTicks(553),
                            RoleName = "Sinh viên",
                            UpdatedAt = new DateTime(2025, 12, 10, 2, 21, 21, 898, DateTimeKind.Utc).AddTicks(554)
                        },
                        new
                        {
                            RoleId = "RL0002",
                            CreatedAt = new DateTime(2025, 12, 10, 2, 21, 21, 898, DateTimeKind.Utc).AddTicks(558),
                            RoleName = "Giảng viên",
                            UpdatedAt = new DateTime(2025, 12, 10, 2, 21, 21, 898, DateTimeKind.Utc).AddTicks(559)
                        },
                        new
                        {
                            RoleId = "RL0003",
                            CreatedAt = new DateTime(2025, 12, 10, 2, 21, 21, 898, DateTimeKind.Utc).AddTicks(562),
                            RoleName = "Quản trị viên cơ sở vật chất",
                            UpdatedAt = new DateTime(2025, 12, 10, 2, 21, 21, 898, DateTimeKind.Utc).AddTicks(563)
                        });
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("user_id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("EmailVerificationCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("email_verification_code");

                    b.Property<DateTime?>("EmailVerificationCodeExpiry")
                        .HasColumnType("datetime2")
                        .HasColumnName("email_verification_code_expiry");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("IsVerify")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Unverified")
                        .HasColumnName("is_verify");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("PasswordResetCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("password_reset_code");

                    b.Property<DateTime?>("PasswordResetCodeExpiry")
                        .HasColumnType("datetime2")
                        .HasColumnName("password_reset_code_expiry");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("user_name");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[user_name] IS NOT NULL");

                    b.ToTable("user", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "U00001",
                            CreatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 62, DateTimeKind.Utc).AddTicks(9346),
                            Email = "student@fpt.edu.vn",
                            FullName = "Nguyễn Văn A",
                            IsVerify = "Unverified",
                            Password = "$2a$11$mlzqNVf8XuIw.eibGsBbJeuQb0ZeCtJ77vBc60Fq6.hjNrsi3hcXi",
                            RoleId = "RL0001",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 62, DateTimeKind.Utc).AddTicks(9350),
                            UserName = "studentA"
                        },
                        new
                        {
                            UserId = "U00002",
                            CreatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 218, DateTimeKind.Utc).AddTicks(7151),
                            Email = "lecturer@fe.edu.vn",
                            FullName = "Trần Thị B",
                            IsVerify = "Unverified",
                            Password = "$2a$11$H1wfehj8lGSH.s5Eg2IeeuIRd7WCj1iVvchDoxI4BUgVEkxroCTFO",
                            RoleId = "RL0002",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 218, DateTimeKind.Utc).AddTicks(7157),
                            UserName = "lecturerB"
                        },
                        new
                        {
                            UserId = "U00003",
                            CreatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 374, DateTimeKind.Utc).AddTicks(5306),
                            Email = "admin@fpt.edu.vn",
                            FullName = "Quản trị viên hệ thống",
                            IsVerify = "Unverified",
                            Password = "$2a$11$jc4YFPVjpTDLT2WFK3s3DezqwDolDoqe1BTjTUbb3k7TRMSaIOjN2",
                            RoleId = "RL0003",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 12, 10, 2, 21, 22, 374, DateTimeKind.Utc).AddTicks(5311),
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("DAL.Models.Booking", b =>
                {
                    b.HasOne("DAL.Models.User", "Approver")
                        .WithMany("ApprovedBookings")
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DAL.Models.Facility", "Facility")
                        .WithMany("Bookings")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Facility");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.BookingFeedback", b =>
                {
                    b.HasOne("DAL.Models.Booking", "Booking")
                        .WithOne("Feedback")
                        .HasForeignKey("DAL.Models.BookingFeedback", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.Facility", b =>
                {
                    b.HasOne("DAL.Models.Campus", "Campus")
                        .WithMany("Facilities")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "FacilityManager")
                        .WithMany("ManagedFacilities")
                        .HasForeignKey("FacilityManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DAL.Models.FacilityType", "FacilityType")
                        .WithMany("Facilities")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campus");

                    b.Navigation("FacilityManager");

                    b.Navigation("FacilityType");
                });

            modelBuilder.Entity("DAL.Models.Notification", b =>
                {
                    b.HasOne("DAL.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DAL.Models.BookingFeedback", "Feedback")
                        .WithMany()
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", null)
                        .WithMany("Notifications")
                        .HasForeignKey("UserId1");

                    b.Navigation("Booking");

                    b.Navigation("Feedback");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.HasOne("DAL.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DAL.Models.Booking", b =>
                {
                    b.Navigation("Feedback");
                });

            modelBuilder.Entity("DAL.Models.Campus", b =>
                {
                    b.Navigation("Facilities");
                });

            modelBuilder.Entity("DAL.Models.Facility", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("DAL.Models.FacilityType", b =>
                {
                    b.Navigation("Facilities");
                });

            modelBuilder.Entity("DAL.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Navigation("ApprovedBookings");

                    b.Navigation("Bookings");

                    b.Navigation("ManagedFacilities");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
