// <auto-generated />
using System;
using DAL.Dbcontext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(FacilityBookingDbContext))]
    partial class FacilityBookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.Booking", b =>
                {
                    b.Property<string>("BookingId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("booking_id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("approved_by");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("check_in_time");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("check_out_time");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_time");

                    b.Property<int?>("EstimatedAttendees")
                        .HasColumnType("int")
                        .HasColumnName("estimated_attendees");

                    b.Property<string>("FacilityId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("facility_id");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<string>("Purpose")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("purpose");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("SpecialRequirements")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("special_requirements");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("user_id");

                    b.HasKey("BookingId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("UserId");

                    b.HasIndex("FacilityId", "StartTime", "EndTime", "Status");

                    b.ToTable("booking", (string)null);
                });

            modelBuilder.Entity("DAL.Models.BookingFeedback", b =>
                {
                    b.Property<string>("FeedbackId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("feedback_id");

                    b.Property<string>("BookingId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("booking_id");

                    b.Property<string>("Comments")
                        .HasColumnType("text")
                        .HasColumnName("comments");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("IssueDescription")
                        .HasColumnType("text")
                        .HasColumnName("issue_description");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<bool>("ReportIssue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("report_issue");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("resolved_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("user_id");

                    b.HasKey("FeedbackId");

                    b.HasIndex("BookingId");

                    b.HasIndex("UserId");

                    b.ToTable("booking_feedback", (string)null);
                });

            modelBuilder.Entity("DAL.Models.BookingHistory", b =>
                {
                    b.Property<string>("HistoryId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("history_id");

                    b.Property<string>("BookingId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("FieldChanged")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("field_changed");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("modified_by");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("reason");

                    b.HasKey("HistoryId");

                    b.HasIndex("BookingId");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("booking_history", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Campus", b =>
                {
                    b.Property<string>("CampusId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("campus_id");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FacilityManagerId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("facility_manager_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("CampusId");

                    b.HasIndex("FacilityManagerId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("campus", (string)null);

                    b.HasData(
                        new
                        {
                            CampusId = "C0001",
                            Address = "Lô E2a-7, Đường D1, Khu Công nghệ cao, P.Long Thạnh Mỹ, Tp. Thủ Đức, TP.HCM",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "daihocfpt@fpt.edu.vn",
                            Name = "FPTU HCM Campus",
                            PhoneNumber = "028 7300 5588",
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CampusId = "C0002",
                            Address = "Khu đô thị Nhơn Hội, TP. Quy Nhơn, Bình Định",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "qn@fpt.edu.vn",
                            Name = "FPTU Quy Nhơn Campus",
                            PhoneNumber = "0256 3842 468",
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("DAL.Models.Facility", b =>
                {
                    b.Property<string>("FacilityId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("facility_id");

                    b.Property<string>("Amenities")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("amenities");

                    b.Property<string>("CampusId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("campus_id");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FacilityManagerId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("facility_manager_id");

                    b.Property<string>("FloorNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("floor_number");

                    b.Property<int>("MaxConcurrentBookings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("max_concurrent_bookings");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("RoomNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("room_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("status");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("type_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("FacilityId");

                    b.HasIndex("CampusId");

                    b.HasIndex("FacilityManagerId");

                    b.HasIndex("Name");

                    b.HasIndex("Status");

                    b.HasIndex("TypeId");

                    b.HasIndex("CampusId", "Name")
                        .IsUnique();

                    b.ToTable("facility", (string)null);

                    b.HasData(
                        new
                        {
                            FacilityId = "F00001",
                            Amenities = "{\"projector\": true, \"whiteboard\": true, \"airConditioner\": true, \"speakers\": true}",
                            CampusId = "C0001",
                            Capacity = 40,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phòng học tiêu chuẩn tầng 1",
                            FloorNumber = "1",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng 101",
                            RoomNumber = "101",
                            Status = "Available",
                            TypeId = "FT0001",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FacilityId = "F00002",
                            Amenities = "{\"projector\": true, \"whiteboard\": true, \"airConditioner\": true}",
                            CampusId = "C0001",
                            Capacity = 50,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phòng học lớn tầng 1",
                            FloorNumber = "1",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng 102",
                            RoomNumber = "102",
                            Status = "Available",
                            TypeId = "FT0001",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FacilityId = "F00003",
                            Amenities = "{\"projector\": true, \"whiteboard\": true, \"airConditioner\": true}",
                            CampusId = "C0001",
                            Capacity = 45,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phòng học tầng 2",
                            FloorNumber = "2",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng 201",
                            RoomNumber = "201",
                            Status = "Available",
                            TypeId = "FT0001",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FacilityId = "F00004",
                            Amenities = "{\"projector\": true, \"whiteboard\": true, \"videoConference\": true}",
                            CampusId = "C0001",
                            Capacity = 15,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phòng họp nhỏ",
                            FloorNumber = "2",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng Họp A",
                            RoomNumber = "A201",
                            Status = "Available",
                            TypeId = "FT0002",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FacilityId = "F00005",
                            Amenities = "{\"projector\": true, \"whiteboard\": true, \"videoConference\": true}",
                            CampusId = "C0001",
                            Capacity = 20,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phòng họp vừa",
                            FloorNumber = "2",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng Họp B",
                            RoomNumber = "B201",
                            Status = "Available",
                            TypeId = "FT0002",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FacilityId = "F00006",
                            Amenities = "{\"computers\": 30, \"projector\": true, \"airConditioner\": true, \"printers\": 2}",
                            CampusId = "C0001",
                            Capacity = 30,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phòng thực hành máy tính",
                            FloorNumber = "3",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng Lab 1",
                            RoomNumber = "LAB1",
                            Status = "Available",
                            TypeId = "FT0003",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FacilityId = "F00007",
                            Amenities = "{\"computers\": 30, \"projector\": true, \"airConditioner\": true}",
                            CampusId = "C0001",
                            Capacity = 30,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phòng thực hành lập trình",
                            FloorNumber = "3",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng Lab 2",
                            RoomNumber = "LAB2",
                            Status = "Available",
                            TypeId = "FT0003",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FacilityId = "F00008",
                            Amenities = "{\"scoreBoard\": true, \"lighting\": true, \"changeRoom\": true}",
                            CampusId = "C0001",
                            Capacity = 20,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sân bóng rổ ngoài trời",
                            FloorNumber = "Ground",
                            MaxConcurrentBookings = 1,
                            Name = "Sân Bóng Rổ",
                            RoomNumber = "COURT-BB1",
                            Status = "Available",
                            TypeId = "FT0004",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FacilityId = "F00009",
                            Amenities = "{\"lighting\": true, \"changeRoom\": true}",
                            CampusId = "C0001",
                            Capacity = 10,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sân cầu lông trong nhà",
                            FloorNumber = "Ground",
                            MaxConcurrentBookings = 1,
                            Name = "Sân Cầu Lông",
                            RoomNumber = "COURT-BD1",
                            Status = "Available",
                            TypeId = "FT0004",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FacilityId = "F00010",
                            Amenities = "{\"projector\": true, \"soundSystem\": true, \"stage\": true, \"airConditioner\": true, \"recording\": true}",
                            CampusId = "C0001",
                            Capacity = 200,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hội trường lớn cho sự kiện",
                            FloorNumber = "1",
                            MaxConcurrentBookings = 1,
                            Name = "Hội Trường Chính",
                            RoomNumber = "AUD-MAIN",
                            Status = "Available",
                            TypeId = "FT0005",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FacilityId = "F00011",
                            Amenities = "{\"projector\": true, \"whiteboard\": true, \"airConditioner\": true}",
                            CampusId = "C0002",
                            Capacity = 40,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phòng học tầng 1 - QN",
                            FloorNumber = "1",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng QN-101",
                            RoomNumber = "QN-101",
                            Status = "Available",
                            TypeId = "FT0001",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FacilityId = "F00012",
                            Amenities = "{\"projector\": true, \"whiteboard\": true, \"airConditioner\": true}",
                            CampusId = "C0002",
                            Capacity = 35,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phòng học tầng 1 - QN",
                            FloorNumber = "1",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng QN-102",
                            RoomNumber = "QN-102",
                            Status = "Available",
                            TypeId = "FT0001",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FacilityId = "F00013",
                            Amenities = "{\"projector\": true, \"whiteboard\": true, \"airConditioner\": true}",
                            CampusId = "C0002",
                            Capacity = 40,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phòng học tầng 2 - QN",
                            FloorNumber = "2",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng QN-201",
                            RoomNumber = "QN-201",
                            Status = "Available",
                            TypeId = "FT0001",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FacilityId = "F00014",
                            Amenities = "{\"projector\": true, \"whiteboard\": true, \"airConditioner\": true}",
                            CampusId = "C0002",
                            Capacity = 45,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phòng học tầng 2 - QN",
                            FloorNumber = "2",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng QN-202",
                            RoomNumber = "QN-202",
                            Status = "Available",
                            TypeId = "FT0001",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FacilityId = "F00015",
                            Amenities = "{\"projector\": true, \"whiteboard\": true, \"videoConference\": true}",
                            CampusId = "C0002",
                            Capacity = 12,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phòng họp nhóm",
                            FloorNumber = "3",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng Họp QN-A",
                            RoomNumber = "QN-A301",
                            Status = "Available",
                            TypeId = "FT0002",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FacilityId = "F00016",
                            Amenities = "{\"projector\": true, \"whiteboard\": true, \"videoConference\": true}",
                            CampusId = "C0002",
                            Capacity = 20,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phòng họp lớn",
                            FloorNumber = "3",
                            MaxConcurrentBookings = 1,
                            Name = "Phòng Họp QN-B",
                            RoomNumber = "QN-B301",
                            Status = "Available",
                            TypeId = "FT0002",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FacilityId = "F00017",
                            Amenities = "{\"computers\": 35, \"projector\": true, \"airConditioner\": true, \"printers\": 2}",
                            CampusId = "C0002",
                            Capacity = 35,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phòng thực hành IT",
                            FloorNumber = "4",
                            MaxConcurrentBookings = 1,
                            Name = "Lab QN-1",
                            RoomNumber = "QN-LAB1",
                            Status = "Available",
                            TypeId = "FT0003",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FacilityId = "F00018",
                            Amenities = "{\"computers\": 30, \"projector\": true, \"airConditioner\": true}",
                            CampusId = "C0002",
                            Capacity = 30,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phòng thực hành software",
                            FloorNumber = "4",
                            MaxConcurrentBookings = 1,
                            Name = "Lab QN-2",
                            RoomNumber = "QN-LAB2",
                            Status = "Available",
                            TypeId = "FT0003",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FacilityId = "F00019",
                            Amenities = "{\"lighting\": true, \"scoreBoard\": true}",
                            CampusId = "C0002",
                            Capacity = 14,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sân bóng đá mini ngoài trời",
                            FloorNumber = "Ground",
                            MaxConcurrentBookings = 1,
                            Name = "Sân Bóng Đá Mini",
                            RoomNumber = "QN-COURT-F1",
                            Status = "Available",
                            TypeId = "FT0004",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FacilityId = "F00020",
                            Amenities = "{\"projector\": true, \"soundSystem\": true, \"stage\": true, \"airConditioner\": true}",
                            CampusId = "C0002",
                            Capacity = 150,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hội trường campus Quy Nhơn",
                            FloorNumber = "1",
                            MaxConcurrentBookings = 1,
                            Name = "Hội Trường QN",
                            RoomNumber = "QN-AUD",
                            Status = "Available",
                            TypeId = "FT0005",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("DAL.Models.FacilityImage", b =>
                {
                    b.Property<string>("ImageId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("image_id");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("FacilityId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("facility_id");

                    b.Property<byte?>("ImageOrder")
                        .HasColumnType("tinyint")
                        .HasColumnName("image_order");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("image_url");

                    b.Property<DateTime>("UploadDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("upload_date")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("ImageId");

                    b.HasIndex("FacilityId");

                    b.ToTable("facility_images", (string)null);
                });

            modelBuilder.Entity("DAL.Models.FacilityMaintenance", b =>
                {
                    b.Property<string>("MaintenanceId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("maintenance_id");

                    b.Property<DateTime?>("ActualEnd")
                        .HasColumnType("datetime2")
                        .HasColumnName("actual_end");

                    b.Property<DateTime?>("ActualStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("actual_start");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("assigned_to");

                    b.Property<string>("CompletionNotes")
                        .HasColumnType("text")
                        .HasColumnName("completion_notes");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FacilityId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("facility_id");

                    b.Property<string>("IssueType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("issue_type");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Medium")
                        .HasColumnName("priority");

                    b.Property<DateTime?>("ScheduledEnd")
                        .HasColumnType("datetime2")
                        .HasColumnName("scheduled_end");

                    b.Property<DateTime?>("ScheduledStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("scheduled_start");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("MaintenanceId");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("FacilityId");

                    b.ToTable("facility_maintenance", (string)null);
                });

            modelBuilder.Entity("DAL.Models.FacilityType", b =>
                {
                    b.Property<string>("TypeId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("type_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DefaultAmenities")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("default_amenities");

                    b.Property<int?>("DefaultCapacity")
                        .HasColumnType("int")
                        .HasColumnName("default_capacity");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("icon_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int?>("TypicalDurationHours")
                        .HasColumnType("int")
                        .HasColumnName("typical_duration_hours");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("TypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("facility_type", (string)null);

                    b.HasData(
                        new
                        {
                            TypeId = "FT0001",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultAmenities = "{\"projector\": true, \"whiteboard\": true, \"airConditioner\": true}",
                            DefaultCapacity = 40,
                            Description = "Standard classroom for lectures and seminars",
                            IconUrl = "/icons/classroom.svg",
                            Name = "Classroom",
                            TypicalDurationHours = 2,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TypeId = "FT0002",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultAmenities = "{\"projector\": true, \"whiteboard\": true, \"videoConference\": true}",
                            DefaultCapacity = 15,
                            Description = "Meeting room for group discussions",
                            IconUrl = "/icons/meeting-room.svg",
                            Name = "Meeting Room",
                            TypicalDurationHours = 1,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TypeId = "FT0003",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultAmenities = "{\"computers\": true, \"projector\": true, \"airConditioner\": true, \"printers\": true}",
                            DefaultCapacity = 30,
                            Description = "Computer laboratory with workstations",
                            IconUrl = "/icons/computer-lab.svg",
                            Name = "Computer Lab",
                            TypicalDurationHours = 3,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TypeId = "FT0004",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultAmenities = "{\"scoreBoard\": true, \"lighting\": true, \"changeRoom\": true}",
                            DefaultCapacity = 20,
                            Description = "Sports court for basketball, volleyball, etc.",
                            IconUrl = "/icons/sports-court.svg",
                            Name = "Sports Court",
                            TypicalDurationHours = 2,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TypeId = "FT0005",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultAmenities = "{\"projector\": true, \"soundSystem\": true, \"stage\": true, \"airConditioner\": true}",
                            DefaultCapacity = 200,
                            Description = "Large auditorium for events and presentations",
                            IconUrl = "/icons/auditorium.svg",
                            Name = "Auditorium",
                            TypicalDurationHours = 3,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("DAL.Models.Notification", b =>
                {
                    b.Property<string>("NotificationId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("notification_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("read_at");

                    b.Property<int?>("RelatedEntityId")
                        .HasColumnType("int")
                        .HasColumnName("related_entity_id");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("related_entity_type");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("IsRead");

                    b.HasIndex("UserId");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Report", b =>
                {
                    b.Property<string>("ReportId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("report_id");

                    b.Property<int>("ApprovedBookings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("approved_bookings");

                    b.Property<decimal>("AvgRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("avg_rating");

                    b.Property<string>("BusiestDay")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("busiest_day");

                    b.Property<string>("CampusId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("campus_id");

                    b.Property<int>("CompletedBookings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("completed_bookings");

                    b.Property<string>("FacilityId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("facility_id");

                    b.Property<DateTime>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("generated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("GeneratedBy")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("generated_by");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_published");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PeakHours")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("peak_hours");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("period_type");

                    b.Property<int>("RejectedBookings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("rejected_bookings");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("report_name");

                    b.Property<DateTime>("ReportPeriodEnd")
                        .HasColumnType("datetime2")
                        .HasColumnName("report_period_end");

                    b.Property<DateTime>("ReportPeriodStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("report_period_start");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("report_type");

                    b.Property<int>("TotalBookings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("total_bookings");

                    b.Property<int>("UniqueUsers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("unique_users");

                    b.Property<decimal>("UtilizationRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("utilization_rate");

                    b.HasKey("ReportId");

                    b.HasIndex("CampusId");

                    b.HasIndex("FacilityId");

                    b.HasIndex("GeneratedBy");

                    b.ToTable("report", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Role", b =>
                {
                    b.Property<string>("RoleId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("role_name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("role", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = "RL0001",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleName = "Student",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = "RL0002",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleName = "Lecturer",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = "RL0003",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleName = "Facility_Admin",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("user_id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("CampusId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("campus_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("EmailVerificationCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("email_verification_code");

                    b.Property<DateTime?>("EmailVerificationCodeExpiry")
                        .HasColumnType("datetime2")
                        .HasColumnName("email_verification_code_expiry");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("IsVerify")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Unverified")
                        .HasColumnName("is_verify");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("PasswordResetCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("password_reset_code");

                    b.Property<DateTime?>("PasswordResetCodeExpiry")
                        .HasColumnType("datetime2")
                        .HasColumnName("password_reset_code_expiry");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("user_name");

                    b.HasKey("UserId");

                    b.HasIndex("CampusId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.HasIndex("Status");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[user_name] IS NOT NULL");

                    b.ToTable("user", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "U00001",
                            CampusId = "C0001",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@fpt.edu.vn",
                            FullName = "System Administrator",
                            IsVerify = "Verified",
                            Password = "$2a$11$yUewVhi38UGe9Hv.pCe1b.PCg4hGj4TPi1zHG7QBlUazl06dN1mp.",
                            RoleId = "RL0003",
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = "U00002",
                            CampusId = "C0001",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lecturer@fpt.edu.vn",
                            FullName = "John Lecturer",
                            IsVerify = "Verified",
                            Password = "$2a$11$LL1zVLOKE5ObIxp4VHb8guUI.nOJSpiT1uxS8thUrKpdA/YvsSOj.",
                            RoleId = "RL0002",
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = "U00003",
                            CampusId = "C0001",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student@fpt.edu.vn",
                            FullName = "Jane Student",
                            IsVerify = "Verified",
                            Password = "$2a$11$Scj24gjHsoxFPCE7X6/eUuvNTZHdUNOjoumu3GeK8KfktIohCW8Dm",
                            RoleId = "RL0001",
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("DAL.Models.Booking", b =>
                {
                    b.HasOne("DAL.Models.User", "Approver")
                        .WithMany("ApprovedBookings")
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DAL.Models.Facility", "Facility")
                        .WithMany("Bookings")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Facility");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.BookingFeedback", b =>
                {
                    b.HasOne("DAL.Models.Booking", "Booking")
                        .WithMany("BookingFeedbacks")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("BookingFeedbacks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.BookingHistory", b =>
                {
                    b.HasOne("DAL.Models.Booking", "Booking")
                        .WithMany("BookingHistories")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "ModifiedByUser")
                        .WithMany("BookingHistories")
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("DAL.Models.Campus", b =>
                {
                    b.HasOne("DAL.Models.User", "FacilityManager")
                        .WithMany("ManagedCampuses")
                        .HasForeignKey("FacilityManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FacilityManager");
                });

            modelBuilder.Entity("DAL.Models.Facility", b =>
                {
                    b.HasOne("DAL.Models.Campus", "Campus")
                        .WithMany("Facilities")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "FacilityManager")
                        .WithMany("ManagedFacilities")
                        .HasForeignKey("FacilityManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DAL.Models.FacilityType", "FacilityType")
                        .WithMany("Facilities")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campus");

                    b.Navigation("FacilityManager");

                    b.Navigation("FacilityType");
                });

            modelBuilder.Entity("DAL.Models.FacilityImage", b =>
                {
                    b.HasOne("DAL.Models.Facility", "Facility")
                        .WithMany("FacilityImages")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("DAL.Models.FacilityMaintenance", b =>
                {
                    b.HasOne("DAL.Models.User", "AssignedToUser")
                        .WithMany("AssignedMaintenances")
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DAL.Models.Facility", "Facility")
                        .WithMany("Maintenances")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedToUser");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("DAL.Models.Notification", b =>
                {
                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.Report", b =>
                {
                    b.HasOne("DAL.Models.Campus", "Campus")
                        .WithMany("Reports")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Models.Facility", "Facility")
                        .WithMany("Reports")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DAL.Models.User", "GeneratedByUser")
                        .WithMany("GeneratedReports")
                        .HasForeignKey("GeneratedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campus");

                    b.Navigation("Facility");

                    b.Navigation("GeneratedByUser");
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.HasOne("DAL.Models.Campus", "Campus")
                        .WithMany("Users")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campus");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DAL.Models.Booking", b =>
                {
                    b.Navigation("BookingFeedbacks");

                    b.Navigation("BookingHistories");
                });

            modelBuilder.Entity("DAL.Models.Campus", b =>
                {
                    b.Navigation("Facilities");

                    b.Navigation("Reports");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DAL.Models.Facility", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("FacilityImages");

                    b.Navigation("Maintenances");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("DAL.Models.FacilityType", b =>
                {
                    b.Navigation("Facilities");
                });

            modelBuilder.Entity("DAL.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Navigation("ApprovedBookings");

                    b.Navigation("AssignedMaintenances");

                    b.Navigation("BookingFeedbacks");

                    b.Navigation("BookingHistories");

                    b.Navigation("Bookings");

                    b.Navigation("GeneratedReports");

                    b.Navigation("ManagedCampuses");

                    b.Navigation("ManagedFacilities");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
